### ISSUE TITLE
Route53 hosted zone lookup failing

### ISSUE THREAD

**Issue by regbo** [libdns/route53#10]
I opened an [issue here](https://github.com/mholt/caddy-dynamicdns/issues/17#issuecomment-1023370316) because it looks like the hosted zone lookup is failing on Route53.

~~It may be related to the domain name I am using (.tm)~~. Having a brief look at the code now.

Here are the logs I am seeing and my IAM policy:
```
{"level":"error","ts":1643296784.4517176,"logger":"dynamic_dns","msg":"unable to lookup current IPs from DNS records","error":"HostedZoneNotFound: No zones found for the domain XXX.tm"}
{"level":"error","ts":1643296803.113794,"logger":"dynamic_dns","msg":"failed setting DNS record(s) with new IP address(es)","zone":"XXX.tm","error":"HostedZoneNotFound: No zones found for the domain XXX.tm"}
```

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "route53:ListResourceRecordSets",
                "route53:GetChange",
                "route53:ChangeResourceRecordSets"
            ],
            "Resource": [
                "arn:aws:route53:::hostedzone/XXX",
                "arn:aws:route53:::change/*"
            ]
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "route53:ListHostedZonesByName",
                "route53:ListHostedZones"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by regbo** [comment]
Somewhere between this library and Caddy there is a miscommunication with trailing dots. My hunch is that somewhere a placeholder ZoneId is being used, and then stripped off without checking if it's a legitimate ZoneId discovered from an IAM policy.

The net-net is, their plugin works if I use the domain XXX.tm**.**, and does not if I remove the trailing dot.

**Comment by tomcrawf90** [comment]
I appear to be having similar problems with Route53 when using as ACME DNS.

```json
{
  "level": "error",
  "ts": 1644260234.9011567,
  "logger": "tls.renew",
  "msg": "could not get certificate from issuer",
  "identifier": "xxx.xxx.wales",
  "issuer": "acme-v02.api.letsencrypt.org-directory",
  "error": "[xxx.xxx.wales] solving challenges: presenting for challenge: adding temporary record for zone wales.: HostedZoneNotFound: No zones found for the domain wales."
}
```

The hosted zone of `xxx.wales` exists and is allowed on the IAM policy. Also an identical Caddy configuration and IAM policy on a different `.com` domain is working without issues.
