### ISSUE TITLE
Issue with txt records mismatched and not being cleaned up

### ISSUE THREAD

**Issue by kwypchlo** [libdns/route53#11]
Hey @PhoenixPeca ! I described my issue on caddy forum but it may seem like it could be connected directly to route53 implementation - could you take a look? It seems that txt records are not being properly cleaned up.

https://caddy.community/t/problem-with-ssl-challenge-dns-01/15255

Let me know if I can provide any more details.

**Comment by aymanbagabas** [comment]
@kwypchlo does this issue still exist on v1.2.1?

**Comment by kwypchlo** [comment]
> @kwypchlo does this issue still exist on v1.2.1?

Sorry but we switched away from caddy a while ago, can't really verify that. I'll close this one since I can't reproduce it right now.

**Comment by mholt** [comment]
@kwypchlo Why did you switch?

**Comment by kwypchlo** [comment]
> @kwypchlo Why did you switch?

First I needed some custom scripting done for some routes (like before and after proxying the request) and switched to openresty for that but left Caddy running as a transparent proxy to handle ssl certs since it was working so well.

Unfortunately I came across those issues with route53 plugin that I tried to solve for a while and they were really silently breaking the domain and required me checking dns records for leftovers every now and then. Additionally, I've been running 50+ machines and letsencrypt rate limited me since all the machines shared couple of domain certs on top of other ones. I know I could have used paid zerossl plan or set up a caddy plugin for storing shared certs on shared disk but at that point it was easier to set up certbot to fetch SAN certificate (and since some of the domains were different letsencrypt treats them as unique thus it's not rate limiting) that caddy was not supporting.

Keep in mind tho that I think Caddy is really top tier project and using nginx after using Caddy feels so last decade. For most projects Caddy should be enough but for the project I'm working on I needed some functionalities that nginx already had, most prominently easy way of custom scripting.

**Comment by mholt** [comment]
Gotcha. Yeah, if the Caddy instances are simply configured to use the same storage backend they will share cert resources and coordinate management automatically. This can be as simple as a shared mounted file system or be a redis or SQL DB or something like that.

> First I needed some custom scripting done for some routes (like before and after proxying the request) and switched to openresty for that 

Can you tell me more about your scripting needs? What did the scripts do? We'll give Caddy feature parity if it doesn't have that already. Thanks for helping me understand!

(Sorry for going off topic)

**Comment by kwypchlo** [comment]
No worries, thank you for a deep dive into the use case :)

So [openresty](https://openresty.org/en/) (preconfigured nginx with lua support baked in) exposes bunch of lifecycle hooks used for scripting - https://openresty-reference.readthedocs.io/en/latest/Directives/ (the diagram is great for explanation).

Couple of examples of usage:

1. to access a content on the project, user can pass what we call a "skylink" in url that can be either base32 or base64 encoded, for logging and caching I wanted to use base64 version always so I needed a way to translate that base32 skylink into base64 early in the request - that's what I used set_by_lua lifecycle hook
2. I want to ratelimit users download/upload on certain endpoints based on their account level (cookie or api key auth) - the way I do it is to make a subrequest to /user/limits endpoint before actually proxying the request to download/upload and set those limits dynamically for each user - this is where I used access_by_lua hook
3. after each file upload I want to make a subrequest to a service that informs the other service that a file has been uploaded to scan it for malware - I want to do it asynchronously, not blocking the request so I used log_by_lua hook that runs after the response is sent and I use nginx timers to fork the long running subrequests in separate processes not to hold workers hostage

Those are just examples but if that would help Caddy project I can prepare all of the use cases I had for custom scripting. 
The project I'm working on has the nginx configuration opensourced so you can take a look at the implementations yourself too https://github.com/SkynetLabs/webportal-nginx

Let me know if you need more information, I'm happy to help!

**Comment by mholt** [comment]
Gotcha, thanks @kwypchlo -- really appreciate the detailed writeup. Sounds like a great candidate for a custom Caddy module and I bet it would perform better than a Lua interpreter. (Would be happy to help implement this for sponsors.)

Again, thanks for the info!
