### ISSUE TITLE
Support not waiting for INSYNC

### ISSUE THREAD

**Issue by mr-karan** [libdns/route53#14]
Can the Provider take an additional option to _not_ wait for the change to be propagated across R53 nameservers? I've noticed that it takes somewhere around ~60s-120s for the change to be set as INSYNC. The response is blocked until this happens. This may not be ideal in usecases like an asynchronous event loop, where different records are sent as individual change set. Waiting for 2 mins for each record update severely bottlenecks the loop.

Maybe the provider option can have a "WaitForPropogation" and set as `true` to maintain backward compatibility.  In case it's set to false, we don't have to [initialize a `water`](https://github.com/libdns/route53/blob/96f2198b3d89c429f4ef3016fdb00172a0d55695/client.go#L253) and can do an early return.

**Comment by aymanbagabas** [comment]
Good point! Feel free to send a PR for this
