### ISSUE TITLE
GetRecords method returning duplicate zone inside record name

### ISSUE THREAD

**Issue by kmei3560** [libdns/route53#22]
I would like to report a possible issue with this library that seems to impact the GetRecords() method.

I work with multiple libdns providers (currently Route53, Azure, GoDaddy) and I've noticed an inconsistency with the AWS library where it seems to return an incorrect record name with the zone duplicated.

Here is an example of records returned (note adjusted domain for privacy):
```
{
	"ID": "",
	"Type": "CNAME",
	"Name": "fxfcgg9qspmn0hc7s0jyrsnytmf5zl7p.testonly-blue.fake.io.fake.io.",
	"Value": "dcv.digicert.com",
	"TTL": 0,
	"Priority": 0
},
{
	"ID": "",
	"Type": "CNAME",
	"Name": "sws11ndn4n7c3pbh3wd7wtkyfj0178dl.testonly-green.fake.io.fake.io.",
	"Value": "dcv.digicert.com",
	"TTL": 0,
	"Priority": 0
},
{
	"ID": "",
	"Type": "CNAME",
	"Name": "tcvp52w241b05r1mt2v6k33qfyhyl8mb.testonly-red.fake.io.fake.io.",
	"Value": "dcv.digicert.com",
	"TTL": 0,
	"Priority": 0
}
```
In my code, I have resorted to the following hacky-workaround to make Route53 perform consistent as the other providers I use:
```
// separate and remove duplicate zone from Route53 GetRecords response
// TODO followup to determine if this is a mistake in libdns/route53
if dnsProvider == "route53" {
	if strings.Contains(rec.Name, zone) {
		rec.Name = strings.ReplaceAll(rec.Name, zone, "") // remove duplicate zone returned in record
	}
}
```

I would like to ask -- has anyone else seen this issue?  If this is a known issue, I can probably hunt it down and submit a PR to fix.
Thank you

**Comment by aymanbagabas** [comment]
Hi @kmei3560, what's the `libdns/route53` version are you using?

**Comment by kmei3560** [comment]
It looks like I'm using v1.2.2 according to my go.mod. If you think this issue may have already been corrected in a newer release - I can definitely upgrade and let you know.
