### ISSUE TITLE
Relative/absolute record name conversions

### ISSUE THREAD

**Issue by mholt** [libdns/route53#3]
Hi,

Over in the libdns repo, we're discussing standardizing the use of relative or absolute record names in `libdns.Record` structs. The current consensus is that they should be made relative (i.e. for a record named `sub.example.com` in a zone called `example.com`, the name should become `sub`). This may affect your provider implementation.

When you have a chance, would you please check out [this issue](https://github.com/libdns/libdns/issues/12#issuecomment-756135908)? This is the last call for feedback before we decide and I push the changes, and I want to make sure we get it right for the majority of DNS provider implementations so we don't have to change it again.

Link: https://github.com/libdns/libdns/issues/12#issuecomment-756135908

Thank you!

**Comment by PhoenixPeca** [comment]
Hi sir @danlsgiga and sir @mholt  ,
I think i'm experiencing this issue as of the moment.. :'(

Here's an entry in my log:
```
{
   "level":"error",
   "ts":1618745949.476079,
   "logger":"tls.obtain",
   "msg":"will retry",
   "error":"[docs-internal.aspac.io] Obtain: [docs-internal.aspac.io] solving challenges: presenting for challenge: adding temporary record for zone aspac.io.: InvalidChangeBatch: InvalidChangeBatch: [RRSet with DNS name _acme-challenge.docs-internal. is not permitted in zone aspac.io.]\n\tstatus code: 400, request id: 8ddcc784-1088-40f1-803b-d25d6d4a41da (order=https://acme.zerossl.com/v2/DV90/order/wtYhV5I8qesI-eO55-Eoag) (ca=https://acme.zerossl.com/v2/DV90)",
   "attempt":6,
   "retrying_in":1200,
   "elapsed":1241.678182843,
   "max_duration":2592000
}
```

**Comment by PhoenixPeca** [comment]
Hi @mholt @danlsgiga I have debugged and spent my entire day trying to solve this problem and I'm so glad I got it fixed. :D Got lucky to have been able to fix another issue with this plugin even though I have no concrete golang background. XD
